# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='done',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='fav',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='usr_id',
        ),
    ]
