# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170611_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('icon', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
