# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0008_auto_20170613_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stat',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stat',
            name='usr_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stat',
            name='post_id',
            field=models.ManyToManyField(to='article.Post'),
        ),
    ]
