# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_auto_20170616_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='usr_id',
        ),
        migrations.AddField(
            model_name='post',
            name='done_usr',
            field=models.ManyToManyField(related_name='user_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='saved_usr',
            field=models.ManyToManyField(related_name='user_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='stat',
        ),
    ]
