# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_arch_euser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('Title', models.TextField()),
                ('msg', models.TextField()),
            ],
        ),
    ]
