# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='Title',
            new_name='title',
        ),
    ]
