# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20170622_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='changes',
            field=models.ManyToManyField(to='article.Msg'),
        ),
    ]
